# Generated by Django 5.2.6 on 2025-12-23 09:23

import autoslug.fields
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0003_rename_newsfrom_newstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, null=True, populate_from='cat_name', unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_image',
            field=image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='newsimage/%Y/%m/%d', verbose_name='News Image (1280X720px)'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='subcat_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, null=True, populate_from='subcat_name', unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
    ]
